version: "2.4"
services:
  example:
    restart: unless-stopped
    build: .
    pids_limit: 256
    mem_limit: 64M
    cpus: 0.5
    ports:
      - 1338:5000

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    environment:
      - DELETE_AFTER=30m
      - SLEEP=30m

